#ifndef BONGO_CAT_WINDOW_WHEEL_INTERNAL_H
#define BONGO_CAT_WINDOW_WHEEL_INTERNAL_H

#define BONGO_CAT_WHEEL_GESTURE_IDLE_NS 120000000ull
#define BONGO_CAT_WHEEL_FRAME_INTERVAL_NS 8000000ull

int bongo_cat_window_wheel_round_position(float value);

#endif
