#ifndef BONGO_CAT_PREFERENCES_ICONS_H
#define BONGO_CAT_PREFERENCES_ICONS_H

#include <stdbool.h>

#include "nuklear_config.h"

typedef enum BongoCatPrefIcon {
    BONGO_CAT_PREF_ICON_SECTION_WINDOW,
    BONGO_CAT_PREF_ICON_SECTION_MODEL,
    BONGO_CAT_PREF_ICON_SECTION_APPLICATION,
    BONGO_CAT_PREF_ICON_SECTION_APPEARANCE,
    BONGO_CAT_PREF_ICON_MULTIPLE_MODELS,
    BONGO_CAT_PREF_ICON_PASS_THROUGH,
    BONGO_CAT_PREF_ICON_ALWAYS_ON_TOP,
    BONGO_CAT_PREF_ICON_SOLID_BACKGROUND,
    BONGO_CAT_PREF_ICON_WINDOW_SIZE,
    BONGO_CAT_PREF_ICON_WINDOW_CORNERS,
    BONGO_CAT_PREF_ICON_OPACITY,
    BONGO_CAT_PREF_ICON_RANDOM_EXPRESSION,
    BONGO_CAT_PREF_ICON_RANDOM_MOTION,
    BONGO_CAT_PREF_ICON_MIRROR,
    BONGO_CAT_PREF_ICON_MOUSE_MIRROR,
    BONGO_CAT_PREF_ICON_MOUSE_CENTERED,
    BONGO_CAT_PREF_ICON_IGNORE_MOUSE,
    BONGO_CAT_PREF_ICON_TEXTURE_RESOLUTION,
    BONGO_CAT_PREF_ICON_MAX_FPS,
    BONGO_CAT_PREF_ICON_RENDER_QUALITY,
    BONGO_CAT_PREF_ICON_AUTOSTART,
    BONGO_CAT_PREF_ICON_ADMINISTRATOR,
    BONGO_CAT_PREF_ICON_LANGUAGE,
    BONGO_CAT_PREF_ICON_THEME,
    BONGO_CAT_PREF_ICON_SHORTCUT_VISIBILITY,
    BONGO_CAT_PREF_ICON_SHORTCUT_PREFERENCES,
    BONGO_CAT_PREF_ICON_SHORTCUT_MENU,
    BONGO_CAT_PREF_ICON_HIDE_FADE,
    BONGO_CAT_PREF_ICON_GAMEPAD_FOUR_HANDS,
    BONGO_CAT_PREF_ICON_VERTICAL_FLIP,
    BONGO_CAT_PREF_ICON_MOUSE_VERTICAL_FLIP,
    BONGO_CAT_PREF_ICON_COUNT
} BongoCatPrefIcon;

void bongo_cat_pref_icon_draw(struct nk_command_buffer *canvas,
    struct nk_rect bounds, BongoCatPrefIcon icon, struct nk_color color);

#endif
