cmake_minimum_required(VERSION 3.24)
include("${CMAKE_CURRENT_LIST_DIR}/CubismShaderOptimize.cmake")
if(NOT DEFINED ROOT)
  get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()
if(NOT DEFINED SDK)
  set(SDK "${ROOT}/vendor/CubismSdkForNative")
endif()
set(shader "${SDK}/Framework/src/Rendering/OpenGL/CubismShader_OpenGLES2.cpp")
if(NOT EXISTS "${shader}")
  message(STATUS "Cubism texture sampling check skipped: local SDK absent")
  return()
endif()
file(READ "${shader}" source)
string(REPLACE "\r\n" "\n" source "${source}")
string(FIND "${source}" "void CubismShader_OpenGLES2::SetupTexture(" begin)
string(FIND "${source}" "void CubismShader_OpenGLES2::SetColorUniformVariables(" end)
if(begin LESS 0 OR end LESS_EQUAL begin)
  message(FATAL_ERROR "Cubism texture setup boundaries changed; review the sampler patch")
endif()
math(EXPR length "${end} - ${begin}")
string(SUBSTRING "${source}" ${begin} ${length} original_setup)
bongo_cat_patch_cubism_texture_sampling(source)
string(FIND "${source}" "void CubismShader_OpenGLES2::SetupTexture(" begin)
string(FIND "${source}" "void CubismShader_OpenGLES2::SetColorUniformVariables(" end)
math(EXPR length "${end} - ${begin}")
string(SUBSTRING "${source}" ${begin} ${length} patched_setup)
if(patched_setup MATCHES "glTexParameteri\\(")
  message(FATAL_ERROR "Cubism still overwrites atlas sampler state during drawing")
endif()
foreach(binding IN ITEMS "glActiveTexture(GL_TEXTURE0);"
    "glBindTexture(GL_TEXTURE_2D, textureId);"
    "glUniform1i(shaderSet->SamplerTexture0Location, 0);")
  string(FIND "${patched_setup}" "${binding}" found)
  if(found EQUAL -1)
    message(FATAL_ERROR "Cubism atlas texture binding removed: ${binding}")
  endif()
endforeach()
# All shader arithmetic, texture lookup, and blending outside SetupTexture
# must remain exactly as supplied by the SDK in this ownership-only patch.
file(READ "${shader}" expected)
string(REPLACE "\r\n" "\n" expected "${expected}")
string(REPLACE "${original_setup}" "${patched_setup}" expected "${expected}")
if(NOT source STREQUAL expected)
  message(FATAL_ERROR "Texture sampling patch changed code outside SetupTexture")
endif()
message(STATUS "Cubism texture sampling ownership passed")
