install(TARGETS bongo_cat
  RUNTIME DESTINATION . COMPONENT Runtime
  BUNDLE DESTINATION . COMPONENT Runtime)
if(UNIX AND NOT APPLE)
  install(DIRECTORY resources/assets DESTINATION . COMPONENT Runtime
    PATTERN "logo-mac.png" EXCLUDE PATTERN "ui-icons.png" EXCLUDE
    PATTERN "ui-symbols-1x.png" EXCLUDE PATTERN "ui-symbols-4x.png" EXCLUDE)
  install(FILES resources/linux/bongo-cat.desktop
    DESTINATION share/applications COMPONENT Runtime)
  install(FILES resources/icons/512x512.png
    DESTINATION share/icons/hicolor/512x512/apps RENAME bongo-cat.png COMPONENT Runtime)
  install(FILES resources/icons/128x128.png
    DESTINATION share/icons/hicolor/128x128/apps RENAME bongo-cat.png COMPONENT Runtime)
endif()

if(CMAKE_SIZEOF_VOID_P EQUAL 8)
  set(BONGO_CAT_PACKAGE_ARCH "x64")
else()
  set(BONGO_CAT_PACKAGE_ARCH "x86")
endif()

if(APPLE)
  if(CMAKE_OSX_ARCHITECTURES)
    list(LENGTH CMAKE_OSX_ARCHITECTURES BONGO_CAT_OSX_ARCH_COUNT)
    if(BONGO_CAT_OSX_ARCH_COUNT GREATER 1)
      set(BONGO_CAT_PACKAGE_ARCH "universal")
    else()
      list(GET CMAKE_OSX_ARCHITECTURES 0 BONGO_CAT_OSX_ARCH)
      if(BONGO_CAT_OSX_ARCH MATCHES "^(arm64|aarch64)$")
        set(BONGO_CAT_PACKAGE_ARCH "arm64")
      endif()
    endif()
  elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(arm64|aarch64|ARM64)$")
    set(BONGO_CAT_PACKAGE_ARCH "arm64")
  endif()
  set(BONGO_CAT_PACKAGE_PLATFORM "macos-${BONGO_CAT_PACKAGE_ARCH}")
  set(CPACK_GENERATOR "ZIP")
elseif(WIN32)
  set(BONGO_CAT_PACKAGE_PLATFORM "windows-${BONGO_CAT_PACKAGE_ARCH}")
  set(CPACK_GENERATOR "ZIP")
else()
  if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(arm64|aarch64|ARM64)$")
    set(BONGO_CAT_PACKAGE_ARCH "arm64")
  endif()
  set(BONGO_CAT_PACKAGE_PLATFORM "linux-${BONGO_CAT_PACKAGE_ARCH}")
  set(CPACK_GENERATOR "TGZ")
endif()

set(BONGO_CAT_PACKAGE_NAME
  "BongoCat-${PROJECT_VERSION}-${BONGO_CAT_PACKAGE_PLATFORM}")
file(GENERATE OUTPUT "${CMAKE_BINARY_DIR}/bongo-cat-package-name.txt"
  CONTENT "${BONGO_CAT_PACKAGE_NAME}\n")

set(CPACK_PACKAGE_NAME "BongoCat")
set(CPACK_PACKAGE_VENDOR "BongoCat")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "${PROJECT_DESCRIPTION}")
set(CPACK_PACKAGE_HOMEPAGE_URL "${PROJECT_HOMEPAGE_URL}")
set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")
set(CPACK_PACKAGE_FILE_NAME "${BONGO_CAT_PACKAGE_NAME}")
set(CPACK_PACKAGE_DIRECTORY "${CMAKE_BINARY_DIR}/dist")
set(CPACK_PACKAGE_CHECKSUM "SHA256")
set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY ON)
set(CPACK_INSTALL_CMAKE_PROJECTS
  "${CMAKE_BINARY_DIR};${PROJECT_NAME};Runtime;/")
include(CPack)
