set(BONGO_CAT_RUNTIME_INTERNAL_INCLUDE_DIRS
  "${CMAKE_CURRENT_SOURCE_DIR}/src/runtime"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/runtime/lifecycle"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/runtime/model"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/runtime/model/import"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/runtime/model/import/mver"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/runtime/model/import/nearby"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/runtime/shell"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/runtime/update"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/ui/backend"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/ui/preferences"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/ui/rendering"
  "${CMAKE_CURRENT_SOURCE_DIR}/src/ui/theme")

set(BONGO_CAT_MEDIA_SOURCES
  src/media/audio.c
  src/media/image.c
  src/media/image_decode.c
  src/media/image_info.c
  src/media/image_mipmap.c
  src/media/image_resize.c
  src/media/image_alpha.c
  src/media/stb_image_impl.c)

set(BONGO_CAT_RENDER_SOURCES
  src/render/gl_api.c
  src/render/overlay.c
  src/render/overlay_draw.c
  src/render/mver_pointer_overlay.c
  src/render/mver_pointer_overlay_draw.c)

set(BONGO_CAT_RUNTIME_LIFECYCLE_SOURCES
  src/runtime/lifecycle/app.c
  src/runtime/lifecycle/app_entry.c
  src/runtime/lifecycle/app_input.c
  src/runtime/lifecycle/app_loop.c
  src/runtime/lifecycle/assets.c
  src/runtime/lifecycle/config_store.c
  src/runtime/lifecycle/frame_clock.c
  src/runtime/lifecycle/memory_policy.c
  src/runtime/lifecycle/runtime_flow.c
  src/runtime/lifecycle/runtime_state.c
  src/runtime/lifecycle/shutdown.c
  src/runtime/lifecycle/startup.c
  src/runtime/lifecycle/startup_arguments.c
  src/runtime/lifecycle/system_language.c
  src/runtime/lifecycle/storage_paths.c)

set(BONGO_CAT_RUNTIME_UPDATE_SOURCES
  src/runtime/update/update_channel.c
  src/runtime/update/update_http.c
  src/runtime/update/update_http_unix.c
  src/runtime/update/update_service.c)

set(BONGO_CAT_RUNTIME_DIAGNOSTIC_SOURCES
  src/runtime/diagnostics/frame_audit.c
  src/runtime/diagnostics/frame_presentation_audit.c
  src/runtime/diagnostics/live2d_audit.c
  src/runtime/diagnostics/live2d_pointer_audit.c
  src/runtime/diagnostics/live2d_audit_scenario.c
  src/runtime/diagnostics/live2d_viewer_audit.c
  src/runtime/diagnostics/live2d_viewer_timing.c
  src/runtime/diagnostics/live2d_visual_audit.c)

set(BONGO_CAT_RUNTIME_INPUT_SOURCES
  src/runtime/input/gamepad.c
  src/runtime/input/mouse.c
  src/runtime/input/mouse_diagnostics.c
  src/runtime/input/mouse_mapping.c
  src/runtime/input/mouse_pipeline.c
  src/runtime/input/shortcuts.c)

set(BONGO_CAT_RUNTIME_MODEL_SOURCES
  src/runtime/model/model_behavior_cache.c
  src/runtime/model/model_behavior_state.c
  src/runtime/model/model_catalog_runtime.c
  src/runtime/model/model_catalog_builtins.c
  src/runtime/model/model_catalog_commit.c
  src/runtime/model/model_catalog_remove.c
  src/runtime/model/model_catalog_refresh.c
  src/runtime/model/model_catalog_selection.c
  src/runtime/model/model_cover.c
  src/runtime/model/model_cover_queue.c
  src/runtime/model/model_files.c
  src/runtime/model/model_geometry.c
  src/runtime/model/multi_pet.c
  src/runtime/model/multi_pet_selection.c
  src/runtime/model/multi_pet_process.c
  src/runtime/model/multi_pet_settings.c
  src/runtime/model/model_storage.c
  src/runtime/model/model_update.c)

set(BONGO_CAT_RUNTIME_IMPORT_SOURCES
  # Shared import workflow.
  src/runtime/model/import/model_import_app.c
  src/runtime/model/import/model_import_adapter.c
  src/runtime/model/import/model_import_digest.c
  src/runtime/model/import/model_import_digest_api.c
  src/runtime/model/import/model_import_digest_cache.c
  src/runtime/model/import/model_import_digest_path.c
  src/runtime/model/import/model_import_discover.c
  src/runtime/model/import/model_import_manifest.c
  src/runtime/model/import/model_import_identity.c
  src/runtime/model/import/model_import_installed.c
  src/runtime/model/import/model_import_install.c
  src/runtime/model/import/model_import_lock.c
  src/runtime/model/import/model_import_metadata.c
  src/runtime/model/import/model_import_package.c
  src/runtime/model/import/model_import_package_index.c
  src/runtime/model/import/model_import_path.c
  src/runtime/model/import/model_import_probe.c
  src/runtime/model/import/model_import_progressive.c
  src/runtime/model/import/model_import_report.c
  src/runtime/model/import/model_import_scan.c
  src/runtime/model/import/model_import_session.c
  src/runtime/model/import/model_import_source.c

  # Mver is the canonical package and runtime-adapter format.
  src/runtime/model/import/mver/model_import_mver_assets.c
  src/runtime/model/import/mver/model_import_mver_copy.c
  src/runtime/model/import/mver/model_import_mver_discovery.c
  src/runtime/model/import/mver/model_import_mver_effect.c
  src/runtime/model/import/mver/model_import_mver_image.c
  src/runtime/model/import/mver/model_import_mver_labels.c
  src/runtime/model/import/mver/model_import_mver_metadata.c
  src/runtime/model/import/mver/model_import_mver_motion.c
  src/runtime/model/import/mver/model_import_mver_patch.c
  src/runtime/model/import/mver/model_import_mver_policy.c
  src/runtime/model/import/mver/model_import_mver_shortcut.c

  # Tauri packages are converted to canonical Mver packages before loading.
  src/runtime/model/import/tauri/model_import_tauri_candidate.c
  src/runtime/model/import/tauri/model_import_tauri_config.c
  src/runtime/model/import/tauri/model_import_tauri_convert.c
  src/runtime/model/import/tauri/model_import_tauri_discovery.c
  src/runtime/model/import/tauri/model_import_tauri_images.c
  src/runtime/model/import/tauri/model_import_tauri_keys.c
  src/runtime/model/import/tauri/model_import_tauri_metadata.c
  src/runtime/model/import/tauri/model_import_tauri_resources.c
  src/runtime/model/import/tauri/model_import_tauri_tree.c

  # Nearby discovery builds adapters without installing source packages.
  src/runtime/model/import/nearby/model_import_nearby.c
  src/runtime/model/import/nearby/model_import_nearby_cache.c
  src/runtime/model/import/nearby/model_import_nearby_signature.c)

set(BONGO_CAT_RUNTIME_SHELL_SOURCES
  src/runtime/shell/modal_frame.c
  src/runtime/shell/tray.c
  src/runtime/shell/window.c
  src/runtime/shell/window_background.c
  src/runtime/shell/window_display.c
  src/runtime/shell/window_drag.c
  src/runtime/shell/window_geometry.c
  src/runtime/shell/window_hit.c
  src/runtime/shell/window_menu_actions.c
  src/runtime/shell/window_menu_behavior.c
  src/runtime/shell/window_menu_behavior_test.c
  src/runtime/shell/window_menu_preview.c
  src/runtime/shell/window_wheel.c
  src/runtime/shell/window_wheel_test.c)

set(BONGO_CAT_UI_BACKEND_SOURCES
  src/ui/backend/nuklear_impl.c
  src/ui/backend/ui_backend.c
  src/ui/backend/ui_backend_fonts.c
  src/ui/backend/ui_cursor.c
  src/ui/backend/ui_input.c
  src/ui/backend/ui_resize_cache.c
  src/ui/backend/ui_scale.c
  src/ui/backend/ui_tooltip.c)

set(BONGO_CAT_UI_RENDERING_SOURCES
  src/ui/rendering/ui_animation.c
  src/ui/rendering/ui_font.c
  src/ui/rendering/ui_font_atlas.c
  src/ui/rendering/ui_font_atlas_ranges.c
  src/ui/rendering/ui_font_atlas_sources.c
  src/ui/rendering/ui_font_atlas_upload.c
  src/ui/rendering/ui_font_reload.c
  src/ui/rendering/ui_native_theme.c
  src/ui/rendering/ui_paint.c
  src/ui/rendering/ui_paint_border.c
  src/ui/rendering/ui_paint_cache.c
  src/ui/rendering/ui_paint_lifecycle.c
  src/ui/rendering/ui_paint_shell.c)

set(BONGO_CAT_UI_THEME_SOURCES
  src/ui/theme/ui_catime.c
  src/ui/theme/ui_catime_icons.c
  src/ui/theme/ui_catime_tabs.c
  src/ui/theme/ui_catime_theme.c)

set(BONGO_CAT_UI_PREFERENCES_SOURCES
  src/ui/preferences/preferences.c
  src/ui/preferences/preferences_about.c
  src/ui/preferences/preferences_about_community.c
  src/ui/preferences/preferences_about_footer.c
  src/ui/preferences/preferences_about_page.c
  src/ui/preferences/preferences_assets.c
  src/ui/preferences/preferences_behavior_dialog.c
  src/ui/preferences/preferences_behavior_rename.c
  src/ui/preferences/preferences_behavior_row.c
  src/ui/preferences/preferences_combo.c
  src/ui/preferences/preferences_controls.c
  src/ui/preferences/preferences_dialog.c
  src/ui/preferences/preferences_form_label.c
  src/ui/preferences/preferences_fonts.c
  src/ui/preferences/preferences_gl.c
  src/ui/preferences/preferences_import.c
  src/ui/preferences/preferences_import_dialog.c
  src/ui/preferences/preferences_import_progress.c
  src/ui/preferences/preferences_import_worker.c
  src/ui/preferences/preferences_icons.c
  src/ui/preferences/preferences_language.c
  src/ui/preferences/preferences_lifecycle.c
  src/ui/preferences/preferences_live_resize.c
  src/ui/preferences/preferences_model.c
  src/ui/preferences/preferences_model_card.c
  src/ui/preferences/preferences_model_card_paint.c
  src/ui/preferences/preferences_model_cover.c
  src/ui/preferences/preferences_model_section.c
  src/ui/preferences/preferences_model_watch.c
  src/ui/preferences/preferences_model_glyphs.c
  src/ui/preferences/preferences_model_import.c
  src/ui/preferences/preferences_model_rename.c
  src/ui/preferences/preferences_notice.c
  src/ui/preferences/preferences_overlay.c
  src/ui/preferences/preferences_page_dispatch.c
  src/ui/preferences/preferences_pages.c
  src/ui/preferences/preferences_present.c
  src/ui/preferences/preferences_render.c
  src/ui/preferences/preferences_row_icons.c
  src/ui/preferences/preferences_scale.c
  src/ui/preferences/preferences_scrollbar.c
  src/ui/preferences/preferences_section_icons.c
  src/ui/preferences/preferences_shortcut_clear.c
  src/ui/preferences/preferences_shortcuts.c
  src/ui/preferences/preferences_smoke.c
  src/ui/preferences/preferences_text_edit.c
  src/ui/preferences/preferences_text_session.c
  src/ui/preferences/preferences_theme.c
  src/ui/preferences/preferences_toggle.c
  src/ui/preferences/preferences_widget_shortcut.c
  src/ui/preferences/preferences_widgets.c
  src/ui/preferences/preferences_widgets_compound.c)

set(BONGO_CAT_RUNTIME_SOURCES
  src/core/app_state.c
  src/platform/common/memory.c
  src/platform/common/update_shutdown.c
  ${BONGO_CAT_MEDIA_SOURCES}
  ${BONGO_CAT_RENDER_SOURCES}
  ${BONGO_CAT_RUNTIME_LIFECYCLE_SOURCES}
  ${BONGO_CAT_RUNTIME_UPDATE_SOURCES}
  ${BONGO_CAT_RUNTIME_DIAGNOSTIC_SOURCES}
  ${BONGO_CAT_RUNTIME_INPUT_SOURCES}
  ${BONGO_CAT_RUNTIME_MODEL_SOURCES}
  ${BONGO_CAT_RUNTIME_IMPORT_SOURCES}
  ${BONGO_CAT_RUNTIME_SHELL_SOURCES}
  ${BONGO_CAT_UI_BACKEND_SOURCES}
  ${BONGO_CAT_UI_RENDERING_SOURCES}
  ${BONGO_CAT_UI_THEME_SOURCES}
  ${BONGO_CAT_UI_PREFERENCES_SOURCES})
